### PR TITLE
Room Support

### LINKED ISSUE #1: Bring over #13 from legacy `sharkiq`
@Mobius5150 has a PR that adds room-level support on the legacy repo https://github.com/ajmarks/sharkiq/pull/13

This issue is being created to track migrating this PR over to the new repo.

### PR DESCRIPTION
**Pull request by ElMoselYEE**
Adding support for rooms.

Closes #1. Full credit to @Mobius5150 for this work. I am simply bringing it to the maintained repo.

Tested a number of scenarios with my personal vacuum, seems to work as intended.

### CODE REVIEW

**Review by funkybunch — APPROVED** [review]
Code lgtm.  Will merge tomorrow once I have a chance to test on my robot as well.

**Comment by funkybunch** [comment]
Thanks @ElMoselYEE & @Mobius5150!

If either of you has time to also implement this in a PR on the Home Assistant Core side that will expedite things.

It's going to be a week or two before I'll have time to tackle that myself.

**Comment by ElMoselYEE** [comment]
I'll try to take a look at what it'll take to get it working in Home Assistant Core, although I've never touched that codebase so might take me a while to get familiar.

**Comment by NickLewanowicz** [comment]
Many people including myself really appreciate this feature! Thanks a ton for putting in the effort 🙇♥️

**Review by JeffResc — APPROVED** [review]

**Comment by funkybunch** [comment]
@JeffResc are we waiting for `codecov` to behave before merging this?  If not I think we should go ahead and merge this in.

**Comment by JeffResc** [comment]
@funkybunch I think it's safe to ignore Codecov in this case and proceed with merging this. Thank you @ElMoselYEE for your hard work on this PR! My only thought it that we should definitely coordinate these changes being implemented in Home Assistant core, but I'm not sure what that would look like.

**Comment by ElMoselYEE** [comment]
Thanks. Incorporating into HA is on my mind but based on my current workload, I can't really predict when I'd be able to set aside enough time to accomplish that.

The only progress I've actually made is I know that the Roborock S7 vacuum has room-level support, and there's an [example here](https://www.reddit.com/r/homeassistant/comments/v1rgqn/heres_my_clean_vacuummop_card/) of a Reddit user incorporating that functionality into a card. So my plan was to reverse-engineer how that vacuum integration works, how rooms are exposed to HA, and attempt to port that over to use this Shark API.

**Comment by funkybunch** [comment]
Let's go ahead and merge these changes and we'll coordinate the dependency feature bump with the next update to HA.

**Pull request merged**
